from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand

from api import create_app, db
from api.database.models import Report, Comment
from tests import db_drop_everything

app = create_app()
migrate = Migrate(app, db)
manager = Manager(app)

# manage migrations
manager.add_command('db', MigrateCommand)



@manager.command
def routes():
    print(app.url_map)


@manager.command
def db_seed():
    db_drop_everything(db)
    db.create_all()

    # seed anything here we might need
    report1 = Report(name='Phil', lat=39.3912345, long=-104.5212345, description='Saw some stuff', event_type='sighting', city="Denver", state="CO", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg')
    report2 = Report(name='Phil', lat=39.4312345, long=-104.5012345, description='Saw some stuff', event_type='sighting', city="Denver", state="CO", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg')
    report3 = Report(name='Phil', lat=39.4112345, long=-104.5612345, description='Saw some stuff', event_type='sighting', city="Denver", state="CO", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg')
    report4 = Report(name='Phil', lat=39.4512345, long=-104.5212345, description='Saw some stuff', event_type='sighting', city="Denver", state="CO", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg')
    report5 = Report(name='Austin', lat=39.4512345, long=-104.5812345, description='talked to some greys', event_type='contact', city="Denver", state="CO", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg')
    report6 = Report(name='Austin', lat=39.3912345, long=-104.4612345, description='talked to some greys', event_type='contact', city="Denver", state="CO", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg')
    report7 = Report(name='Austin', lat=39.3712345, long=-104.5412345, description='talked to some greys', event_type='contact', city="Denver", state="CO", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg')
    report8 = Report(name='Austin', lat=39.4112345, long=-104.4412345, description='talked to some greys', event_type='contact', city="Denver", state="CO", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg')
    report9 = Report(name='Hanna', lat=39.4312345, long=-104.5812345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg')
    report10 = Report(name='Hanna', lat=39.3712345, long=-104.4812345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg')
    report11 = Report(name='Hanna', lat=39.3512345, long=-104.4612345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg')
    report12 = Report(name='Hanna', lat=39.3312345, long=-104.4412345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg')
    report13 = Report(name='Phil',   lat=36.1912345, long=-86.7212345, description='Saw some stuff', event_type='sighting', city="Nashville", state="TN", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg')
    report14 = Report(name='Phil',   lat=36.2312345, long=-86.7012345, description='Saw some stuff', event_type='sighting', city="Nashville", state="TN", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg')
    report15 = Report(name='Phil',   lat=36.2112345, long=-86.7612345, description='Saw some stuff', event_type='sighting', city="Nashville", state="TN", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg')
    report16 = Report(name='Phil',   lat=36.2512345, long=-86.7212345, description='Saw some stuff', event_type='sighting', city="Nashville", state="TN", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg')
    report17 = Report(name='Austin', lat=36.2512345, long=-86.7812345, description='talked to some greys', event_type='contact', city="Nashville", state="TN", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg')
    report18 = Report(name='Austin', lat=36.1912345, long=-86.6612345, description='talked to some greys', event_type='contact', city="Nashville", state="TN", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg')
    report19 = Report(name='Austin', lat=36.1712345, long=-86.7412345, description='talked to some greys', event_type='contact', city="Nashville", state="TN", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg')
    report20 = Report(name='Austin', lat=36.2112345, long=-86.6412345, description='talked to some greys', event_type='contact', city="Nashville", state="TN", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg')
    report21 = Report(name='Hanna',  lat=36.2312345, long=-86.7812345, description='it was chill', event_type='abduction', city="Nashville", state="TN", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg')
    report22 = Report(name='Hanna',  lat=36.1712345, long=-86.6812345, description='it was chill', event_type='abduction', city="Nashville", state="TN", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg')
    report23 = Report(name='Hanna',  lat=36.1512345, long=-86.6612345, description='it was chill', event_type='abduction', city="Nashville", state="TN", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg')
    report24 = Report(name='Hanna',  lat=36.1312345, long=-86.6412345, description='it was chill', event_type='abduction', city="Nashville", state="TN", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg')
    db.session.add(report1)
    db.session.add(report2)
    db.session.add(report3)
    db.session.add(report4)
    db.session.add(report5)
    db.session.add(report6)
    db.session.add(report7)
    db.session.add(report8)
    db.session.add(report9)
    db.session.add(report10)
    db.session.add(report11)
    db.session.add(report12)
    db.session.add(report13)
    db.session.add(report14)
    db.session.add(report15)
    db.session.add(report16)
    db.session.add(report17)
    db.session.add(report18)
    db.session.add(report19)
    db.session.add(report20)
    db.session.add(report21)
    db.session.add(report22)
    db.session.add(report23)
    db.session.add(report24)

    db.session.commit()

    comment1 = Comment(report_id=report1.id, text="that's crazy dude")
    comment2 = Comment(report_id=report1.id, text="you're smokin dream sand")
    comment3 = Comment(report_id=report2.id, text="that's crazy dude")
    comment4 = Comment(report_id=report2.id, text="you're smokin dream sand")
    comment5 = Comment(report_id=report3.id, text="that's crazy dude")
    comment6 = Comment(report_id=report3.id, text="you're smokin dream sand")
    comment7 = Comment(report_id=report4.id, text="that's crazy dude")
    comment8 = Comment(report_id=report4.id, text="you're smokin dream sand")
    comment9 = Comment(report_id=report5.id, text="that's crazy dude")
    comment10 = Comment(report_id=report5.id, text="you're smokin dream sand")
    comment11 = Comment(report_id=report6.id, text="that's crazy dude")
    comment12 = Comment(report_id=report6.id, text="you're smokin dream sand")
    comment13 = Comment(report_id=report7.id, text="that's crazy dude")
    comment14 = Comment(report_id=report7.id, text="you're smokin dream sand")
    comment15 = Comment(report_id=report8.id, text="that's crazy dude")
    comment16 = Comment(report_id=report8.id, text="you're smokin dream sand")
    comment17 = Comment(report_id=report9.id, text="that's crazy dude")
    comment18 = Comment(report_id=report9.id, text="you're smokin dream sand")
    comment19 = Comment(report_id=report10.id, text="that's crazy dude")
    comment20 = Comment(report_id=report10.id, text="you're smokin dream sand")
    comment21 = Comment(report_id=report11.id, text="that's crazy dude")
    comment22 = Comment(report_id=report11.id, text="you're smokin dream sand")
    comment23 = Comment(report_id=report12.id, text="that's crazy dude")
    comment24 = Comment(report_id=report12.id, text="you're smokin dream sand")
    comment25 = Comment(report_id=report13.id, text="that's crazy dude")
    comment26 = Comment(report_id=report13.id, text="you're smokin dream sand")
    comment27 = Comment(report_id=report14.id, text="that's crazy dude")
    comment28 = Comment(report_id=report14.id, text="you're smokin dream sand")
    comment29 = Comment(report_id=report15.id, text="that's crazy dude")
    comment30 = Comment(report_id=report15.id, text="you're smokin dream sand")
    comment31 = Comment(report_id=report16.id, text="that's crazy dude")
    comment32 = Comment(report_id=report16.id, text="you're smokin dream sand")
    comment33 = Comment(report_id=report17.id, text="that's crazy dude")
    comment34 = Comment(report_id=report17.id, text="you're smokin dream sand")
    comment35 = Comment(report_id=report18.id, text="that's crazy dude")
    comment36 = Comment(report_id=report18.id, text="you're smokin dream sand")
    comment37 = Comment(report_id=report19.id, text="that's crazy dude")
    comment38 = Comment(report_id=report19.id, text="you're smokin dream sand")
    comment39 = Comment(report_id=report20.id, text="that's crazy dude")
    comment40 = Comment(report_id=report20.id, text="you're smokin dream sand")
    comment41 = Comment(report_id=report21.id, text="that's crazy dude")
    comment42 = Comment(report_id=report21.id, text="you're smokin dream sand")
    comment43 = Comment(report_id=report22.id, text="that's crazy dude")
    comment44 = Comment(report_id=report22.id, text="you're smokin dream sand")
    comment45 = Comment(report_id=report23.id, text="that's crazy dude")
    comment46 = Comment(report_id=report23.id, text="you're smokin dream sand")
    comment47 = Comment(report_id=report24.id, text="that's crazy dude")
    comment48 = Comment(report_id=report24.id, text="you're smokin dream sand")

    db.session.add(comment1)
    db.session.add(comment2)
    db.session.add(comment3)
    db.session.add(comment4)
    db.session.add(comment5)
    db.session.add(comment6)
    db.session.add(comment7)
    db.session.add(comment8)
    db.session.add(comment9)
    db.session.add(comment10)
    db.session.add(comment11)
    db.session.add(comment12)
    db.session.add(comment13)
    db.session.add(comment14)
    db.session.add(comment15)
    db.session.add(comment16)
    db.session.add(comment17)
    db.session.add(comment18)
    db.session.add(comment19)
    db.session.add(comment20)
    db.session.add(comment21)
    db.session.add(comment22)
    db.session.add(comment23)
    db.session.add(comment24)
    db.session.add(comment25)
    db.session.add(comment26)
    db.session.add(comment27)
    db.session.add(comment28)
    db.session.add(comment29)
    db.session.add(comment30)
    db.session.add(comment31)
    db.session.add(comment32)
    db.session.add(comment33)
    db.session.add(comment34)
    db.session.add(comment35)
    db.session.add(comment36)
    db.session.add(comment37)
    db.session.add(comment38)
    db.session.add(comment39)
    db.session.add(comment40)
    db.session.add(comment41)
    db.session.add(comment42)
    db.session.add(comment43)
    db.session.add(comment44)
    db.session.add(comment45)
    db.session.add(comment46)
    db.session.add(comment47)
    db.session.add(comment48)
    db.session.commit()
    print(f'obj count: {len(db.session.query(Report).all())}')
    print(f'obj count: {len(db.session.query(Comment).all())}')


if __name__ == "__main__":
    manager.run()
