from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand

from api import create_app, db
from api.database.models import Report, Comment
from tests import db_drop_everything
from datetime import datetime

app = create_app()
migrate = Migrate(app, db)
manager = Manager(app)

# manage migrations
manager.add_command('db', MigrateCommand)



@manager.command
def routes():
    print(app.url_map)


@manager.command
def db_seed():
    db_drop_everything(db)
    db.create_all()

    #Denver Area:
    # +1 days ago:
    report1 = Report(name='', lat=39.3912345, long=-104.5212345, description='Saw some stuff', event_type='sighting', city="Denver", state="CO", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg', created_at=datetime(2021, 2, 28,12,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report2 = Report(name='Phil', lat=39.4312345, long=-104.5012345, description='Saw some stuff', event_type='sighting', city="Denver", state="CO", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg', created_at=datetime(2021, 2, 27,13,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report3 = Report(name='', lat=39.4112345, long=-104.5612345, description='Saw some stuff', event_type='sighting', city="Denver", state="CO", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg', created_at=datetime(2021, 2, 27,14,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report4 = Report(name='Phil', lat=39.4512345, long=-104.5212345, description='Saw some stuff', event_type='sighting', city="Denver", state="CO", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg', created_at=datetime(2021, 2, 28,15,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report5 = Report(name='Austin', lat=39.4512345, long=-104.5812345, description='talked to some greys', event_type='contact', city="Denver", state="CO", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg', created_at=datetime(2021, 2, 26,16,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report6 = Report(name='', lat=39.3912345, long=-104.4612345, description='talked to some greys', event_type='contact', city="Denver", state="CO", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg', created_at=datetime(2021, 2, 26,17,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report7 = Report(name='Austin', lat=39.3712345, long=-104.5412345, description='talked to some greys', event_type='contact', city="Denver", state="CO", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg', created_at=datetime(2021, 2, 28,18,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report8 = Report(name='', lat=39.4112345, long=-104.4412345, description='talked to some greys', event_type='contact', city="Denver", state="CO", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg', created_at=datetime(2021, 2, 27,19,00).strftime("%m/%d/%Y, %H:%M:%S"))
    # +8 days ago
    report9 = Report(name='Hanna', lat=39.4312345, long=-104.5812345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 21,12,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report10 = Report(name='', lat=39.3712345, long=-104.4812345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 20,13,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report11 = Report(name='Hanna', lat=39.3512345, long=-104.4612345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 21,14,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report12 = Report(name='', lat=39.3312345, long=-104.4412345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 19,15,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report25 = Report(name='Todd', lat=39.3922345, long=-104.4412345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 21,16,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report26 = Report(name='', lat=39.3932345, long=-104.4412345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 20,17,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report27 = Report(name='Todd', lat=39.3942345, long=-104.4412345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 19,18,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report28 = Report(name='', lat=39.3952345, long=-104.4412345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 21,19,00).strftime("%m/%d/%Y, %H:%M:%S"))
    # +30 days ago:
    report33 = Report(name='Hanna', lat=39.4442345, long=-104.5892345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 31,12,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report34 = Report(name='', lat=39.3622345, long=-104.4892345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 30,13,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report35 = Report(name='Hanna', lat=39.3532345, long=-104.4752345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 29,14,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report36 = Report(name='', lat=39.3362345, long=-104.4392345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 28,15,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report37 = Report(name='Todd', lat=39.3882345, long=-104.4642345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 27,16,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report38 = Report(name='', lat=39.3802345, long=-104.4262345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 26,17,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report39 = Report(name='Todd', lat=39.3872345, long=-104.4392345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 25,18,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report40 = Report(name='', lat=39.3902345, long=-104.4499345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 24,19,00).strftime("%m/%d/%Y, %H:%M:%S"))
    #Nashville area:
    # +1 days ago:
    report13 = Report(name='Phil',   lat=36.1912345, long=-86.7212345, description='Saw some stuff', event_type='sighting', city="Nashville", state="TN", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg', created_at=datetime(2021, 2, 28,12,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report14 = Report(name='',   lat=36.2312345, long=-86.7012345, description='Saw some stuff', event_type='sighting', city="Nashville", state="TN", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg', created_at=datetime(2021, 2, 27,13,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report15 = Report(name='Phil',   lat=36.2112345, long=-86.7612345, description='Saw some stuff', event_type='sighting', city="Nashville", state="TN", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg', created_at=datetime(2021, 2, 26,14,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report16 = Report(name='',   lat=36.2512345, long=-86.7212345, description='Saw some stuff', event_type='sighting', city="Nashville", state="TN", image='https://s.hdnux.com/photos/01/00/16/14/16835374/9/1200x0.jpg', created_at=datetime(2021, 2, 28,15,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report17 = Report(name='Austin', lat=36.2512345, long=-86.7812345, description='talked to some greys', event_type='contact', city="Nashville", state="TN", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg', created_at=datetime(2021, 2, 27,16,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report18 = Report(name='', lat=36.1912345, long=-86.6612345, description='talked to some greys', event_type='contact', city="Nashville", state="TN", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg', created_at=datetime(2021, 2, 26,17,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report19 = Report(name='Austin', lat=36.1712345, long=-86.7412345, description='talked to some greys', event_type='contact', city="Nashville", state="TN", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg', created_at=datetime(2021, 2, 28,18,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report20 = Report(name='', lat=36.2112345, long=-86.6412345, description='talked to some greys', event_type='contact', city="Nashville", state="TN", image='https://cdn.mos.cms.futurecdn.net/oafrH5eR2xkEjm55LS9gVM.jpg', created_at=datetime(2021, 2, 27,19,00).strftime("%m/%d/%Y, %H:%M:%S"))
    # +8 days ago
    report21 = Report(name='Hanna',  lat=36.2312345, long=-86.7812345, description='it was chill', event_type='abduction', city="Nashville", state="TN", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 21,12,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report22 = Report(name='',  lat=36.1712345, long=-86.6812345, description='it was chill', event_type='abduction', city="Nashville", state="TN", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 20,13,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report23 = Report(name='Hanna',  lat=36.1512345, long=-86.6612345, description='it was chill', event_type='abduction', city="Nashville", state="TN", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 20,14,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report24 = Report(name='',  lat=36.1312345, long=-86.6412345, description='it was chill', event_type='abduction', city="Nashville", state="TN", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 19,15,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report29 = Report(name='Todd', lat=36.3922345, long=-86.4412345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 20,16,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report30 = Report(name='', lat=36.3932345, long=-86.4412345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 21,17,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report31 = Report(name='Todd', lat=36.3942345, long=-86.4412345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 21,18,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report32 = Report(name='', lat=36.3952345, long=-86.4412345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 2, 19,19,00).strftime("%m/%d/%Y, %H:%M:%S"))
    #30 days ago
    report41 = Report(name='Hanna', lat=36.3362345, long=-86.4412345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 31,12,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report42 = Report(name='', lat=36.3752345, long=-86.4312345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 30,13,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report43 = Report(name='Hanna', lat=36.3552345, long=-86.4312345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 29,14,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report44 = Report(name='', lat=36.3912345, long=-86.4112345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 28,15,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report45 = Report(name='Todd', lat=36.3992345, long=-86.4812345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 27,16,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report46 = Report(name='', lat=36.3652345, long=-86.4012345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 26,17,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report47 = Report(name='Todd', lat=36.3992345, long=-86.4372345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 25,18,00).strftime("%m/%d/%Y, %H:%M:%S"))
    report48 = Report(name='', lat=36.3752345, long=-86.4452345, description='it was chill', event_type='abduction', city="Denver", state="CO", image='https://images-na.ssl-images-amazon.com/images/I/41%2BA5ZsPnHL._AC_SX425_.jpg', created_at=datetime(2021, 1, 24,19,00).strftime("%m/%d/%Y, %H:%M:%S"))
    db.session.add(report1)
    db.session.add(report2)
    db.session.add(report3)
    db.session.add(report4)
    db.session.add(report5)
    db.session.add(report6)
    db.session.add(report7)
    db.session.add(report8)
    db.session.add(report9)
    db.session.add(report10)
    db.session.add(report11)
    db.session.add(report12)
    db.session.add(report13)
    db.session.add(report14)
    db.session.add(report15)
    db.session.add(report16)
    db.session.add(report17)
    db.session.add(report18)
    db.session.add(report19)
    db.session.add(report20)
    db.session.add(report21)
    db.session.add(report22)
    db.session.add(report23)
    db.session.add(report24)
    db.session.add(report25)
    db.session.add(report26)
    db.session.add(report27)
    db.session.add(report28)
    db.session.add(report29)
    db.session.add(report30)
    db.session.add(report31)
    db.session.add(report32)
    db.session.add(report33)
    db.session.add(report34)
    db.session.add(report35)
    db.session.add(report36)
    db.session.add(report37)
    db.session.add(report38)
    db.session.add(report39)
    db.session.add(report40)
    db.session.add(report41)
    db.session.add(report42)
    db.session.add(report43)
    db.session.add(report44)
    db.session.add(report45)
    db.session.add(report46)
    db.session.add(report47)
    db.session.add(report48)

    db.session.commit()

    comment1 = Comment(report_id=report1.id, text="that's crazy dude")
    comment2 = Comment(report_id=report1.id, text="you're smokin that dream sand")
    comment65 = Comment(report_id=report1.id, text="fake news")
    comment66 = Comment(report_id=report1.id, text="sounds legit")
    comment67 = Comment(report_id=report1.id, text="whaaaaaaat")
    comment73 = Comment(report_id=report1.id, text="wild")
    comment3 = Comment(report_id=report2.id, text="that's crazy dude")
    comment4 = Comment(report_id=report2.id, text="you're smokin that dream sand")
    comment5 = Comment(report_id=report3.id, text="that's crazy dude")
    comment6 = Comment(report_id=report3.id, text="you're smokin that dream sand")
    comment7 = Comment(report_id=report4.id, text="that's crazy dude")
    comment8 = Comment(report_id=report4.id, text="you're smokin that dream sand")
    comment68 = Comment(report_id=report4.id, text="incredible")
    comment69 = Comment(report_id=report4.id, text="im jealous")
    comment9 = Comment(report_id=report5.id, text="that's crazy dude")
    comment10 = Comment(report_id=report5.id, text="you're smokin that dream sand")
    comment11 = Comment(report_id=report6.id, text="that's crazy dude")
    comment12 = Comment(report_id=report6.id, text="you're smokin that dream sand")
    comment13 = Comment(report_id=report7.id, text="that's crazy dude")
    comment70 = Comment(report_id=report7.id, text="I want to believe")
    comment71 = Comment(report_id=report7.id, text="I do believe")
    comment14 = Comment(report_id=report7.id, text="you're smokin that dream sand")
    comment15 = Comment(report_id=report8.id, text="that's crazy dude")
    comment16 = Comment(report_id=report8.id, text="you're smokin that dream sand")
    comment17 = Comment(report_id=report9.id, text="that's crazy dude")
    comment18 = Comment(report_id=report9.id, text="you're smokin that dream sand")
    comment19 = Comment(report_id=report10.id, text="that's crazy dude")
    comment72 = Comment(report_id=report10.id, text="sure")
    comment20 = Comment(report_id=report10.id, text="you're smokin that dream sand")
    comment21 = Comment(report_id=report11.id, text="that's crazy dude")
    comment22 = Comment(report_id=report11.id, text="you're smokin that dream sand")
    comment23 = Comment(report_id=report12.id, text="that's crazy dude")
    comment24 = Comment(report_id=report12.id, text="you're smokin that dream sand")
    comment25 = Comment(report_id=report13.id, text="that's crazy dude")
    comment26 = Comment(report_id=report13.id, text="you're smokin that dream sand")
    comment27 = Comment(report_id=report14.id, text="that's crazy dude")
    comment28 = Comment(report_id=report14.id, text="you're smokin that dream sand")
    comment29 = Comment(report_id=report15.id, text="that's crazy dude")
    comment30 = Comment(report_id=report15.id, text="you're smokin that dream sand")
    comment31 = Comment(report_id=report16.id, text="that's crazy dude")
    comment32 = Comment(report_id=report16.id, text="you're smokin that dream sand")
    comment33 = Comment(report_id=report17.id, text="that's crazy dude")
    comment34 = Comment(report_id=report17.id, text="you're smokin that dream sand")
    comment35 = Comment(report_id=report18.id, text="that's crazy dude")
    comment36 = Comment(report_id=report18.id, text="you're smokin that dream sand")
    comment37 = Comment(report_id=report19.id, text="that's crazy dude")
    comment38 = Comment(report_id=report19.id, text="you're smokin that dream sand")
    comment39 = Comment(report_id=report20.id, text="that's crazy dude")
    comment40 = Comment(report_id=report20.id, text="you're smokin that dream sand")
    comment41 = Comment(report_id=report21.id, text="that's crazy dude")
    comment42 = Comment(report_id=report21.id, text="you're smokin that dream sand")
    comment43 = Comment(report_id=report22.id, text="that's crazy dude")
    comment44 = Comment(report_id=report22.id, text="you're smokin that dream sand")
    comment45 = Comment(report_id=report23.id, text="that's crazy dude")
    comment46 = Comment(report_id=report23.id, text="you're smokin that dream sand")
    comment47 = Comment(report_id=report24.id, text="that's crazy dude")
    comment48 = Comment(report_id=report24.id, text="you're smokin that dream sand")
    comment49 = Comment(report_id=report25.id, text="that's crazy dude")
    comment50 = Comment(report_id=report25.id, text="you're smokin that dream sand")
    comment51 = Comment(report_id=report26.id, text="that's crazy dude")
    comment52 = Comment(report_id=report26.id, text="you're smokin that dream sand")
    comment53 = Comment(report_id=report27.id, text="that's crazy dude")
    comment54 = Comment(report_id=report27.id, text="you're smokin that dream sand")
    comment55 = Comment(report_id=report28.id, text="that's crazy dude")
    comment56 = Comment(report_id=report28.id, text="you're smokin that dream sand")
    comment57 = Comment(report_id=report29.id, text="that's crazy dude")
    comment58 = Comment(report_id=report29.id, text="you're smokin that dream sand")
    comment59 = Comment(report_id=report30.id, text="that's crazy dude")
    comment60 = Comment(report_id=report30.id, text="you're smokin that dream sand")
    comment61 = Comment(report_id=report31.id, text="that's crazy dude")
    comment62 = Comment(report_id=report31.id, text="you're smokin that dream sand")
    comment63 = Comment(report_id=report32.id, text="that's crazy dude")
    comment64 = Comment(report_id=report32.id, text="you're smokin that dream sand")
    comment74 = Comment(report_id=report33.id, text="that's crazy dude")
    comment75 = Comment(report_id=report33.id, text="you're smokin that dream sand")
    comment76 = Comment(report_id=report34.id, text="that's crazy dude")
    comment77 = Comment(report_id=report34.id, text="you're smokin that dream sand")
    comment78 = Comment(report_id=report35.id, text="that's crazy dude")
    comment79 = Comment(report_id=report35.id, text="you're smokin that dream sand")
    comment80 = Comment(report_id=report36.id, text="that's crazy dude")
    comment81 = Comment(report_id=report36.id, text="you're smokin that dream sand")
    comment82 = Comment(report_id=report37.id, text="that's crazy dude")
    comment83 = Comment(report_id=report37.id, text="you're smokin that dream sand")
    comment84 = Comment(report_id=report38.id, text="that's crazy dude")
    comment85 = Comment(report_id=report38.id, text="you're smokin that dream sand")
    comment86 = Comment(report_id=report39.id, text="that's crazy dude")
    comment87 = Comment(report_id=report39.id, text="you're smokin that dream sand")
    comment88 = Comment(report_id=report40.id, text="that's crazy dude")
    comment89 = Comment(report_id=report40.id, text="you're smokin that dream sand")
    comment90 = Comment(report_id=report41.id, text="that's crazy dude")
    comment91 = Comment(report_id=report41.id, text="you're smokin that dream sand")
    comment92 = Comment(report_id=report42.id, text="that's crazy dude")
    comment93 = Comment(report_id=report42.id, text="you're smokin that dream sand")
    comment94 = Comment(report_id=report43.id, text="that's crazy dude")
    comment95 = Comment(report_id=report43.id, text="you're smokin that dream sand")
    comment96 = Comment(report_id=report44.id, text="that's crazy dude")
    comment97 = Comment(report_id=report44.id, text="you're smokin that dream sand")
    comment98 = Comment(report_id=report45.id, text="that's crazy dude")
    comment99 = Comment(report_id=report45.id, text="you're smokin that dream sand")
    comment100 = Comment(report_id=report46.id, text="that's crazy dude")
    comment101 = Comment(report_id=report46.id, text="you're smokin that dream sand")
    comment102 = Comment(report_id=report47.id, text="that's crazy dude")
    comment103 = Comment(report_id=report47.id, text="you're smokin that dream sand")

    db.session.add(comment1)
    db.session.add(comment2)
    db.session.add(comment3)
    db.session.add(comment4)
    db.session.add(comment5)
    db.session.add(comment6)
    db.session.add(comment7)
    db.session.add(comment8)
    db.session.add(comment9)
    db.session.add(comment10)
    db.session.add(comment11)
    db.session.add(comment12)
    db.session.add(comment13)
    db.session.add(comment14)
    db.session.add(comment15)
    db.session.add(comment16)
    db.session.add(comment17)
    db.session.add(comment18)
    db.session.add(comment19)
    db.session.add(comment20)
    db.session.add(comment21)
    db.session.add(comment22)
    db.session.add(comment23)
    db.session.add(comment24)
    db.session.add(comment25)
    db.session.add(comment26)
    db.session.add(comment27)
    db.session.add(comment28)
    db.session.add(comment29)
    db.session.add(comment30)
    db.session.add(comment31)
    db.session.add(comment32)
    db.session.add(comment33)
    db.session.add(comment34)
    db.session.add(comment35)
    db.session.add(comment36)
    db.session.add(comment37)
    db.session.add(comment38)
    db.session.add(comment39)
    db.session.add(comment40)
    db.session.add(comment41)
    db.session.add(comment42)
    db.session.add(comment43)
    db.session.add(comment44)
    db.session.add(comment45)
    db.session.add(comment46)
    db.session.add(comment47)
    db.session.add(comment48)
    db.session.add(comment49)
    db.session.add(comment50)
    db.session.add(comment51)
    db.session.add(comment52)
    db.session.add(comment53)
    db.session.add(comment54)
    db.session.add(comment55)
    db.session.add(comment56)
    db.session.add(comment57)
    db.session.add(comment58)
    db.session.add(comment59)
    db.session.add(comment60)
    db.session.add(comment61)
    db.session.add(comment62)
    db.session.add(comment63)
    db.session.add(comment64)
    db.session.add(comment65)
    db.session.add(comment66)
    db.session.add(comment67)
    db.session.add(comment68)
    db.session.add(comment69)
    db.session.add(comment70)
    db.session.add(comment71)
    db.session.add(comment72)
    db.session.add(comment73)
    db.session.add(comment74)
    db.session.add(comment75)
    db.session.add(comment76)
    db.session.add(comment77)
    db.session.add(comment78)
    db.session.add(comment79)
    db.session.add(comment80)
    db.session.add(comment81)
    db.session.add(comment82)
    db.session.add(comment83)
    db.session.add(comment84)
    db.session.add(comment85)
    db.session.add(comment86)
    db.session.add(comment87)
    db.session.add(comment88)
    db.session.add(comment89)
    db.session.add(comment90)
    db.session.add(comment91)
    db.session.add(comment92)
    db.session.add(comment93)
    db.session.add(comment94)
    db.session.add(comment95)
    db.session.add(comment96)
    db.session.add(comment97)
    db.session.add(comment98)
    db.session.add(comment99)
    db.session.add(comment100)
    db.session.add(comment101)
    db.session.add(comment102)
    db.session.add(comment103)
    db.session.commit()
    print(f'obj count: {len(db.session.query(Report).all())}')
    print(f'obj count: {len(db.session.query(Comment).all())}')


if __name__ == "__main__":
    manager.run()
